name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Jalan jam 3 pagi JST / 1 malam WIB
  workflow_dispatch:
  push:
    branches:
      - lang

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Push 3D SVGs to profile-3d branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: profile-3d
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}